<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LockPicker</AssemblyName>
    <RootNamespace>LockPicker</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <!-- Иконка исполняемого файла (.exe) -->
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Встраиваем иконку как ресурс, чтобы задавать её окну во время выполнения -->
    <EmbeddedResource Include="icon.ico" />
  </ItemGroup>

</Project>
